# -*- coding: utf-8 -*-
"""Bouwt onderwerpen-PIN.json voor Pincode 4, hoofdstuk 1 en 2 plus basisvaardigheden."""
import json, sys

# (id, label, hoofdstuk, paragrafen, begrippen, begrippen_via_boek, synoniemen)
O = [
 ("PIN-H1-01","Behoeften en soorten behoeften",1,["1.1","Weet je het nog?"],
  ["behoeften","primaire behoeften","secundaire behoeften"],[],
  ["behoefte","basisbehoeften","noodzakelijke behoeften","overige behoeften","luxe behoeften","oneindige behoeften"]),
 ("PIN-H1-02","Bestedingen, consumeren en zelfvoorziening",1,["1.1","Weet je het nog?"],
  ["bestedingen","zelfvoorziening"],["consumeren"],
  ["besteding","consumptie","uitgaven aan goederen en diensten","zelf produceren"]),
 ("PIN-H1-03","Soorten goederen en diensten",1,["1.1","Weet je het nog?"],
  ["producten","diensten","gebruiksgoederen","verbruiksgoederen"],[],
  ["product","dienst","goederen","duurzame consumptiegoederen","tastbaar","ontastbaar"]),
 ("PIN-H1-04","Doelgroep en koopgedrag",1,["1.1"],
  ["doelgroep","koopgedrag"],[],["doelgroepen","kenmerken van een doelgroep","koopbeslissing"]),
 ("PIN-H1-05","Commerciële en sociale beïnvloeding",1,["1.1","Weet je het nog?"],
  ["commerciële beïnvloeding","sociale beïnvloeding"],[],
  ["commerciële invloed","sociale invloed","beïnvloeding van het koopgedrag"]),
 ("PIN-H1-06","Soorten reclame",1,["1.1","Weet je het nog?"],
  ["commerciële reclame","informatieve reclame","merkreclame","ideële reclame"],["reclame"],
  ["reclamesoort","soort reclame"]),
 ("PIN-H1-07","Marketing en de zes marketinginstrumenten",1,["1.1"],
  ["marketing","marketinginstrumenten","productbeleid","prijsbeleid","plaatsbeleid",
   "promotiebeleid","personeelsbeleid","presentatiebeleid"],[],
  ["6 p's","zes p's","marketinginstrument","marketingmix"]),
 ("PIN-H1-08","Consumentenbescherming",1,["1.1"],
  ["vergelijkend warenonderzoek","keurmerk","productaansprakelijkheid"],[],
  ["keurmerken","consumentenbescherming","positie van de consument"]),
 ("PIN-H1-09","Duurzaam consumeren",1,["1.1"],
  ["duurzaam consumeren"],["ecologische voetafdruk","CO2-uitstoot"],
  ["duurzaam consumeren","duurzamer consumeren","duurzaamheid","fairtrade"]),
 ("PIN-H1-10","Maatschappelijke kosten en opbrengsten",1,["1.1"],
  ["maatschappelijke kosten","maatschappelijke opbrengsten"],["extern effect"],
  ["externe effecten","negatief extern effect","positief extern effect","kosten voor de samenleving"]),
 ("PIN-H1-11","Technologische ontwikkeling",1,["1.1"],
  ["technologische ontwikkeling"],[],["technologie","nieuwe productieprocessen"]),
 ("PIN-H1-12","Inkomen uit arbeid, bezit en overdracht",1,["1.2"],
  ["inkomen uit arbeid","inkomen uit bezit","inkomen uit overdracht"],[],
  ["inkomens uit overdrachten","loon","huur","rente","dividend","uitkering","tegenprestatie"]),
 ("PIN-H1-13","Van brutoloon naar besteedbaar inkomen",1,["1.2"],
  ["loonheffing","besteedbaar inkomen"],["brutoloon","nettoloon","toeslagen"],
  ["loonbelasting","inkomstenbelasting","premies volksverzekeringen","netto-inkomen","bruto-inkomen"]),
 ("PIN-H1-14","Primair en secundair inkomen",1,["1.2"],
  ["primair inkomen","secundair inkomen"],[],
  ["primaire inkomens","secundaire inkomens","bruto inkomen","netto inkomen plus overdrachten"]),
 ("PIN-H1-15","Inkomensverschillen en modaal inkomen",1,["1.2"],
  ["modaal inkomen"],["inkomensverschillen","sociaal minimum"],
  ["modaal","meest voorkomende inkomen","minimuminkomen"]),
 ("PIN-H1-16","Nationaal inkomen",1,["1.2"],
  ["nationaal inkomen"],[],["inkomen per hoofd van de bevolking","nationaal inkomen per inwoner"]),
 ("PIN-H1-17","Lorenzcurve",1,["1.2"],
  ["lorenzcurve"],[],["lorenz-curve","personele inkomensverdeling","inkomensverdeling"]),
 ("PIN-H1-18","Schaarste, middelen en prioriteiten",1,["1.3"],
  ["schaarste","middelen","prioriteiten","vrije goederen"],[],
  ["schaars","schaarse goederen","prioriteiten stellen","vrij goed","niet-schaarse goederen","keuzeprobleem"]),
 ("PIN-H1-19","Welvaart en brede welvaart",1,["1.3"],
  ["welvaart","brede welvaart"],["welzijn"],
  ["materiële welvaart","kwaliteit van leven"]),
 ("PIN-H1-20","Indexcijfer en het CBS",1,["1.3"],
  ["indexcijfer","centraal bureau voor de statistiek (CBS)"],["basisjaar"],
  ["indexcijfers","index","CBS","Centraal Bureau voor de Statistiek"]),
 ("PIN-H1-21","Inflatie en deflatie",1,["1.4"],
  ["inflatie","deflatie"],["oorzaken van inflatie"],
  ["prijsstijging","algemene prijsstijging","prijsdaling","inflatiepercentage"]),
 ("PIN-H1-22","Koopkracht en geldontwaarding",1,["1.4"],
  ["koopkracht","geldontwaarding"],[],
  ["koopkrachtverandering","geld wordt minder waard","reële waarde"]),
 ("PIN-H1-23","Consumentenprijsindexcijfer",1,["1.4"],
  ["consumentenprijs-indexcijfer (cpi)","samengesteld ongewogen indexcijfer"],["wegingsfactor"],
  ["cpi","consumentenprijsindex","samengesteld gewogen indexcijfer","weging","wegingsfactoren",
   "prijsindexcijfer","persoonlijk prijsindexcijfer"]),
 ("PIN-H1-24","Nominale en reële verandering",1,["1.4"],
  ["nominale loonstijging","reële verandering van het loon"],[],
  ["nominale verandering","reële verandering","reële loonstijging","nominaal","reëel",
   "nominale inkomensstijging","reële inkomensstijging"]),
 ("PIN-H1-25","Prijscompensatie en loon-prijsspiraal",1,["1.4"],
  ["prijscompensatie","loon-prijsspiraal"],[],
  ["loonprijsspiraal","cao-loon","loonsverhoging","vakbond"]),

 ("PIN-H2-01","Soorten uitgaven",2,["2.1"],
  ["dagelijkse uitgaven","vaste lasten","incidentele uitgaven"],[],
  ["soorten uitgaven","huishoudelijke uitgaven","vaste uitgaven","eenmalige uitgaven"]),
 ("PIN-H2-02","Budgetteren en het budgetplan",2,["2.1"],
  ["budgetplan"],["budgetteren"],
  ["budget","begroting","inkomsten en uitgaven op elkaar afstemmen","huishoudboekje"]),
 ("PIN-H2-03","Reserveren",2,["2.1"],
  ["reserveren"],[],["reservering","maandelijks opzijzetten","sparen voor een grote uitgave"]),
 ("PIN-H2-04","Nibud en Consumentenbond",2,["2.1"],
  ["nibud","consumentenbond"],[],
  ["Nationaal Instituut voor Budgetvoorlichting","budgetvoorlichting"]),
 ("PIN-H2-05","Sparen en spaarmotieven",2,["2.2"],
  ["sparen","spaarmotieven"],[],
  ["spaarmotief","sparen voor een doel","sparen uit voorzorg","sparen voor de rente","banktegoed"]),
 ("PIN-H2-06","Spaardeposito en enkelvoudige rente",2,["2.2"],
  ["spaardeposito","(enkelvoudige) rente"],[],
  ["enkelvoudige rente","rente","interest","depositorekening","spaarrekening","rentepercentage"]),
 ("PIN-H2-07","Samengestelde rente",2,["2.2"],
  ["samengestelde rente"],[],["rente op rente","rente-op-rente","samengesteld"]),
 ("PIN-H2-08","Nominale en reële rente",2,["2.2"],
  ["nominale rente","reële rente"],[],
  ["nominaal rentepercentage","reëel rentepercentage","rente gecorrigeerd voor inflatie"]),
 ("PIN-H2-09","Beleggen en rendement",2,["2.2"],
  ["beleggen","rendement"],[],
  ["belegging","effecten","aandelen","obligaties","koerswinst","duurzaam beleggen"]),
 ("PIN-H2-10","Lenen, krediet en schuld",2,["2.3","Weet je het nog?"],
  ["lenen","krediet","schuld","aflossen"],["BKR-registratie"],
  ["lening","aflossing","schulden","BKR","kredietregistratie","koopkracht naar voren halen"]),
 ("PIN-H2-11","Leenmotieven",2,["2.3"],
  ["leenmotieven"],[],["leenmotief","reden om te lenen"]),
 ("PIN-H2-12","Kredietkosten",2,["2.3","Weet je het nog?"],
  ["kredietkosten"],["termijnbedrag","looptijd"],
  ["kredietkost","rente en bijkomende kosten","totale kosten van een lening"]),
 ("PIN-H2-13","Kredietvormen bij de bank",2,["2.3"],
  ["consumptief krediet","persoonlijke lening","doorlopend krediet","salariskrediet"],["kredietvormen"],
  ["kredietvorm","rood staan","kredietlimiet"]),
 ("PIN-H2-14","Kredietvormen bij de leverancier",2,["2.3"],
  ["koop op afbetaling","private lease","huurkoop","leasing"],["achteraf betalen"],
  ["leasen","lease","afbetaling","termijnen"]),
 ("PIN-H2-15","Hypothecaire lening",2,["2.3"],
  ["hypothecaire lening"],["onderpand"],
  ["hypotheek","hypotheeklasten","hypotheekrente","starters","doorstromers"]),
 ("PIN-H2-16","Geldfuncties",2,["2.4","Weet je het nog?"],
  ["geldfuncties","geld als ruilmiddel","geld als spaarmiddel","geld als rekenmiddel"],[],
  ["ruilmiddel","spaarmiddel","rekenmiddel","oppotmiddel","functies van geld"]),
 ("PIN-H2-17","Directe en indirecte ruil",2,["2.4","Weet je het nog?"],
  ["directe ruil","indirecte ruil"],[],["ruilen","ruilhandel","product voor product"]),
 ("PIN-H2-18","Chartaal en giraal geld",2,["2.4","Weet je het nog?"],
  ["chartaal geld","giraal geld","elektronisch betalen"],[],
  ["contant geld","contant betalen","pinnen","elektronisch geld","pinpas","internetbankieren"]),
 ("PIN-H2-19","Saldo: debet en credit",2,["2.4","Weet je het nog?"],
  ["saldo","debetsaldo","creditsaldo"],[],
  ["rood staan","tegoed","negatief saldo","positief saldo","bankrekening"]),
 ("PIN-H2-20","Vraag naar en aanbod van geld",2,["2.4"],
  ["vraag naar geld","aanbod van geld"],["geldkringloop"],
  ["vraag naar en aanbod van geld","geldstroom","sparen en lenen in de economie"]),
 ("PIN-H2-21","Rente als prijs van geld en de ECB",2,["2.4"],
  ["rente (prijs van geld)","europese centrale bank (ECB)"],["basisrente"],
  ["prijs van geld","ECB","Europese Centrale Bank","rentestand","renteverhoging","rentedaling"]),
 ("PIN-H2-22","Hoe banken geld verdienen",2,["2.4"],
  ["debetrente","creditrente"],["risico","rentemarge"],
  ["verschil tussen spaarrente en leenrente","marge","risico-opslag"]),

 ("PIN-A-01","Rekenen met percentages",None,["Rekenen"],
  [],["percentage berekenen","bedrag met een percentage berekenen"],
  ["procenten","percentage","procentuele stijging","procentuele daling","korting"]),
 ("PIN-A-02","Rekenen met groeifactoren",None,["Rekenen"],
  [],["groeifactor"],["groeifactoren","vermenigvuldigingsfactor","terugrekenen met een groeifactor"]),
 ("PIN-A-03","Absolute en relatieve verandering vergelijken",None,["Rekenen"],
  [],["absolute verandering","relatieve verandering"],
  ["absoluut","relatief","verschil in euro's versus procenten","toename"]),
 ("PIN-A-04","Omrekenen tussen week, maand en jaar",None,["Rekenen"],
  [],["omrekenen naar een andere periode"],
  ["per week","per maand","per jaar","deel van een jaar","naar rato"]),
]

BUITEN = []
AANDACHT = [
 {"onderwerp":"PIN-H1-14","punt":"De Begrippen-pagina van het boek (blz. 27) plaatst primaire en secundaire inkomens onder §1.1, terwijl alle opgaven erover in §1.2 staan. De onderwerpen volgen de opgaven."},
 {"onderwerp":"PIN-H1-18","punt":"Het boek schrijft 'schaars' en 'prioriteiten stellen', de begrippenlijst 'schaarste' en 'prioriteiten'. Beide vormen staan als synoniem opgenomen."},
 {"onderwerp":"PIN-H1-24","punt":"Het boek schrijft 'nominale verandering' en 'reële verandering', de begrippenlijst 'nominale loonstijging' en 'reële verandering van het loon'. Beide vormen staan als synoniem opgenomen."},
 {"onderwerp":"PIN-H1-05","punt":"Het boek schrijft 'commerciële invloed', de begrippenlijst 'commerciële beïnvloeding'. Beide vormen staan als synoniem opgenomen."},
 {"onderwerp":"PIN-H1-07","punt":"Dit onderwerp bevat acht begrippen (marketing plus de zes P's). Bewuste uitzondering op de richtlijn van twee tot drie begrippen: splitsen levert geen ander fouttype op, het is één vaardigheid."},
 {"onderwerp":"PIN-H1-08","punt":"Alle drie de begrippen staan alleen in de syllabus en niet in het boek. Er is geen enkele opgave bij dit onderwerp: wel leren, nergens oefenen."},
 {"onderwerp":"PIN-H1-11","punt":"Staat in de begrippenlijst maar wordt in hoofdstuk 1 door geen enkele opgave bevraagd."},
 {"onderwerp":"PIN-H1-10","punt":"'Maatschappelijke opbrengsten' staat alleen in de syllabus en niet in het boek; de opgaven gaan uitsluitend over maatschappelijke kosten."},
 {"onderwerp":"PIN-H2-10","punt":"BKR-registratie staat niet in de begrippenlijst. De opgaven (§2.3 opgave 4a en 4b) leggen zelf uit wat het BKR is en bevragen bestaande kennis in een nieuwe situatie; ze blijven daarom binnen de toetsstof."},
 {"onderwerp":"PIN-H2-15","punt":"§2.3 opgave 12b vraagt om een verklaring met vraag en aanbod. Dat is stof uit hoofdstuk 3; zodra hoofdstuk 3 gecodeerd is, kan de opgave daar als kruisverband aan gekoppeld worden."},
 {"onderwerp":"PIN-H2-16","punt":"Pincode noemt het 'geld als spaarmiddel'; Praktische Economie noemt dezelfde functie 'oppotmiddel'. Als synoniem opgenomen zodat de koppeling tussen de boeken niet breekt."},
 {"onderwerp":"PIN-H2-17","punt":"Slechts één opgave binnen hoofdstuk 2 (Weet je het nog?, opgave 1). Weinig oefenmateriaal voor een begrippenpaar dat op het CE regelmatig terugkomt."},
 {"onderwerp":"PIN-H1-06","punt":"Alleen opgave 6 van Weet je het nog? bevraagt de soorten reclame. In paragraaf 1.1 zelf komt er geen enkele opgave over; voor SE-stof is dat weinig oefenmateriaal."},
 {"onderwerp":"PIN-H1-16","punt":"Twee opgaven, beide in de Plusopdrachten. Nationaal inkomen komt in de kernopgaven van paragraaf 1.2 niet terug."},
 {"onderwerp":"PIN-H2-16","punt":"Twee opgaven, beide van het type 'herken de geldfunctie'. Geen enkele opgave vraagt om uitleg of toepassing."},
 {"onderwerp":None,"punt":"Van de 347 opgaven in hoofdstuk 1 en 2 staan er 23 op W-niveau (7 procent). 28 van de 51 onderwerpen hebben geen enkele W-opgave. Feedback op weetniveau moet daarom naar de begrippenlijst verwijzen en niet naar boekopgaven."},
 {"onderwerp":None,"punt":"22 onderwerpen hebben geen enkele opgave met de tag rekenen. Daar kan een leerling met een rekenfout niet naar een oefenopgave binnen het onderwerp zelf worden gestuurd; daarvoor zijn de basisvaardigheden PIN-A-01 tot en met PIN-A-04 bedoeld."},
]

def main(uit):
    ond = []
    for oid, label, hfd, paras, begr, viaboek, syn in O:
        ond.append({
            "id": oid, "label": label, "hoofdstuk": hfd, "paragrafen": paras,
            "begrippen": begr, "begrippen_via_presentatie": viaboek,
            "synoniemen": syn, "wds": [], "aantal_opgaven": 0,
        })
    data = {
        "schema": "remendel-onderwerpen/1",
        "boek": {
            "id": "PIN",
            "titel": "Pincode 4 · vmbo GL/TL",
            "niveau": "4 mavo (GL/TL)",
            "toetsstofcriterium": ("De stof uit het boek, aangevuld met de begrippenlijst bij het vak; "
                "die begrippenlijst is gebaseerd op de syllabus van het centraal examen. Begrippen die wel "
                "in het boek worden behandeld maar niet in de begrippenlijst staan, zijn opgenomen in het "
                "veld begrippen_via_presentatie."),
            "status": "hoofdstuk 1 en 2 plus basisvaardigheden; hoofdstuk 3 t/m 8 nog te doen",
        },
        "onderwerpen": ond,
        "buiten_toetsstof": BUITEN,
        "aandachtspunten": AANDACHT,
    }
    with open(uit, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2); f.write("\n")
    print(f"{len(ond)} onderwerpen weggeschreven naar {uit}")

if __name__ == "__main__":
    main(sys.argv[1])
